import os
import glob
import re

dir_path = '/Users/dineshpabbathi/Desktop/precision'

royal_cta_html = """
    <!-- ═══════════════════════════════════════════════════════════ -->
    <!-- ROYAL CTA                                                   -->
    <!-- ═══════════════════════════════════════════════════════════ -->
    <section class="royal-cta">
        <div class="royal-cta__pattern"></div>
        <div class="container royal-cta__container">
            <div class="royal-cta__content">
                <h2 class="royal-cta__title">Ready to Elevate Your Business?</h2>
                <p class="royal-cta__text">Partner with Precision & Co. for strategic financial guidance, unmatched expertise, and a commitment to your long-term success.</p>
                <a href="contact.html" class="royal-cta__btn">
                    <span>Book a Consultation</span>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14m-7-7 7 7-7 7"/></svg>
                </a>
            </div>
        </div>
    </section>
"""

# HTML files to update (skip intro page 'index.html' and ones already generated by script if possible, actually we updated the python script for industries, let's just rebuild industries)
# Actually, it's safer to update the files manually using regex

html_files = glob.glob(os.path.join(dir_path, '*.html'))
for file in html_files:
    filename = os.path.basename(file)
    if filename == 'index.html': 
        continue # Intro page
    if filename.startswith('industry-'):
        continue # These are rebuilt by build script

    with open(file, 'r') as f:
        content = f.read()

    # If it already has royal-cta, skip
    if 'class="royal-cta"' in content:
        continue

    # If it has the old cta-section (like home.html or services), replace it
    # <section class="cta-section" ... </section>
    content = re.sub(r'<!-- ═══════════════════════════════════════════════════════════ -->\s*<!-- CTA SECTION.*?</section>', royal_cta_html, content, flags=re.DOTALL)
    content = re.sub(r'<section class="cta-section".*?</section>', royal_cta_html, content, flags=re.DOTALL)

    # If it didn't have the old cta, inject it before the footer
    if 'class="royal-cta"' not in content:
        # Check if there is an <main> tag that wraps content, if so inject before footer
        # Let's just find the footer and insert it right above
        footer_idx = content.find('<footer class="footer"')
        if footer_idx != -1:
            # We want to insert it right before the footer block.
            # Look for the footer comment block if it exists
            comment_idx = content.rfind('<!-- ═══════════════════════════════════════════════════════════ -->\s*<!-- FOOTER', 0, footer_idx)
            if comment_idx != -1:
                content = content[:comment_idx] + royal_cta_html + '\n' + content[comment_idx:]
            else:
                content = content[:footer_idx] + royal_cta_html + '\n' + content[footer_idx:]

    with open(file, 'w') as f:
        f.write(content)

print("Royal CTA added to pages.")
